title = "Test"
author = "cognitive-engineering-lab"
repo = "rqst-test"
rq-version = "0.3.0"

[[chapters]]
label = "00-stage"
name = "A"
no-starter = true

[[chapters]]
label = "01-stage"
name = "B"

[[chapters]]
label = "02-stage"
name = "C"
